config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'stores#index'
  resources :stores, only: [:new, :create, :edit, :update, :destroy] do
    collection do
      get 'search'
    end
  end
end

app/models/store.rb
class Store < ActiveRecord::Base
  belongs_to :user
  validates :store_name, :c_card, :e_money, presence: true
  validates :store_name, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :stores
  validates :nickname, presence: true
  validates :nickname, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :move_to_index, except: [:index, :search]

  def index
    @stores = Store.includes(:user).page(params[:page]).per(5).order("created_at DESC")
  end

  def new
    @store = Store.new
  end

  def create
    @store = Store.create(store_name: store_params[:store_name], c_card: store_params[:c_card], e_money: store_params[:e_money], user_id: current_user.id)
    if @store.save
      redirect_to :root
    else
      render("stores/new")
    end
  end

  def edit
    @store = Store.find(params[:id])
  end

  def update
    @store = Store.find(params[:id])
    @store.update(store_params)
    if @store.save
    else
      render("stores/edit")
    end
  end

  def destroy
    store = Store.find(params[:id])
    store.destroy
  end

  def search
    @stores = Store.where('store_name LIKE(?)', "%#{(params[:keyword])}%").limit(10)
  end

  private
  def store_params
    params.permit(:store_name, :c_card, :e_money)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CashlessShare</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
    <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/css/materialize.min.css">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/js/materialize.min.js"></script>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>

  <nav>
    <div class="nav-wrapper blue darken-3">
      <a href="/" class="brand-logo">キャッシュレスシェア</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
      <% if user_signed_in? %>
        <li><%= current_user.nickname %> : </li>
        <li><%= link_to "投稿する", new_store_path %></li>
        <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %> </li>
      <% else %>
        <li><%= link_to "ログイン", new_user_session_path %></li>
        <li><%= link_to "新規登録", new_user_registration_path %><li>
      <% end %>
        <li><%= link_to "検索する", search_stores_path, method: :get %></li>
      </ul>
    </div>
  </nav>

<%= yield %>

</body>
</html>

app/views/stores/destroy.html.erb
<div class="row">
  <div class="col s12 m5 offset-m3">
    <div class="card-panel teal">
      <h4 class="white-text">削除が完了しました</h4>
      <%= link_to '投稿一覧へ戻る', "/", class: "waves-effect waves-light btn  blue darken-3" %>
    </div>
  </div>
</div>

app/views/stores/edit.html.erb
<% if @store.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% @store.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="row">
  <%= form_tag("/stores/#{@store.id}", method: :patch) do %>
  <h4>編集する</h4>
    <div class="row">
      <div class="input-field col s8">
        <input placeholder="店名を入れてください" type="text" class="validate" name="store_name" value="<%= @store.store_name %>" autofocus="true">
        <label for="first_name">店名</label>
      </div>
      <div class="input-field col s8">
        <input placeholder="(例)VISA､マスターカード､UC､アメックス､JCB等・・・" type="text" class="validate" name="c_card" value="<%= @store.c_card %>">
        <label for="first_name">使用できるクレジットカードの種類を入力してください</label>
      </div>
      <div class="input-field col s8">
        <input placeholder="(例)Suica、QUICPay等・・・" type="text" class="validate" name="e_money" value="<%= @store.e_money %>">
        <label for="first_name">使用できる電子マネーの種類を入力してください</label>
        <input type="submit" value="編集">
      </div>
    </div>
  <% end %>
</div>

app/views/stores/index.html.erb
<div class="container">
  <div class="row">
    <% @stores.each do |store| %>
    <div class="col s12 m6 offset-m3">
      <div class="card blue darken-3">
        <div class="card-content white-text">
          <h4>店名</h4>
          <span class="card-title"><%= store.store_name %></span>
          <h6>使用できるクレジットカード</h6>
          <p><%= store.c_card %></p>
          <h6>使用できる電子マネー</h6>
          <p><%= store.e_money %></p>
          <h6>投稿者 : <%= store.user.nickname %></h6>
        </div>
        <% if user_signed_in? %>
        <div class="card-action">
          <%= link_to '編集', "/stores/#{store.id}/edit", method: :get, class: "waves-effect waves-light btn" %>
          <%= link_to '削除', "/stores/#{store.id}", method: :delete, class: "waves-effect waves-light btn" %>
        </div>
        <% end %>
      </div>
    </div>
    <% end %>
  </div>
  <%= paginate(@stores) %>
</div>

app/views/stores/new.html.erb
<% if @store.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% @store.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="row">
  <%= form_tag('/stores', method: :post) do %>
    <h4>投稿する</h4>
    <div class="input-field col s8">
      <input placeholder="店名を入れてください" type="text" class="validate" name="store_name" autofocus="true">
      <label for="first_name">店名</label>
    <div class="row">
      <div class="input-field col s8">
        <input placeholder="(例)VISA､マスターカード､UC､アメックス､JCB等・・・" id="first_name" type="text" class="validate" name="c_card">
        <label for="first_name">使用できるクレジットカードの種類を入力してください</label>
      </div>
      <div class="input-field col s8">
        <input placeholder="(例)Suica、QUICPay等・・・" type="text" class="validate" name="e_money">
        <label for="first_name">使用できる電子マネーの種類を入力してください</label>
        <input type="submit" value="送信">
      </div>
    </div>
  <% end %>
</div>

app/views/stores/search.html.erb
<div class="container">
  <div class="row">
    <%= form_tag('/stores/search', method: :get) do %>
      <div class="col s12 m6 offset-m3">
        <input placeholder="店名で検索" type="text" class="validate" name="keyword" autofocus="true"><button  class="waves-effect waves-light btn"><i class="material-icons">search</i></button>
      </div>
    <% end %>
  </div>
  <div class="row">
    <div class="col s12 m6 offset-m3">
      <h6>検索結果</h6>
    </div>
  </div>
  <div class="row">
    <% @stores.each do |store| %>
    <div class="col s12 m6 offset-m3">
      <div class="card blue darken-3">
        <div class="card-content white-text">
          <h4>店名</h4>
          <span class="card-title"><%= store.store_name %></span>
          <h6>使用できるクレジットカード</h6>
          <p><%= store.c_card %></p>
          <h6>使用できる電子マネー</h6>
          <p><%= store.e_money %></p>
          <h6>投稿者 : <%= store.user.nickname %></h6>
        </div>
        <% if user_signed_in? %>
        <div class="card-action">
          <%= link_to '編集', "/stores/#{store.id}/edit", method: :get, class: "waves-effect waves-light btn" %>
          <%= link_to '削除', "/stores/#{store.id}", method: :delete, class: "waves-effect waves-light btn" %>
        </div>
        <% end %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/stores/update.html.erb
<div class="row">
  <div class="col s12 m5 offset-m3">
    <div class="card-panel teal">
      <h4 class="white-text">編集が完了しました</h4>
      <%= link_to '投稿一覧へ戻る', "/", class: "waves-effect waves-light btn  blue darken-3" %>
    </div>
  </div>
</div>